name: Build & Test
on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ['ubuntu-latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/hydrogen'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build
